### ISSUE TITLE
Keep instrumentation and unit tests separate

### ISSUE THREAD

**Issue by jaredsburrows** [pieces029/android-spock#14]
Is there any reason why the tests "have" to be with the `instrumentation` tests in `androidTest`?

**Comment by AndrewReitz** [comment]
I don't think I understand the question. Could you elaborate more?

**Comment by jaredsburrows** [comment]
`Instrumentation` tests should go into the `androidTest` folder while `unit` tests should go into the `test` folder.

**Comment by AndrewReitz** [comment]
I agree with your statement. I don't understand where it's coming from.

**Comment by jaredsburrows** [comment]
> I don't understand where it's coming from.

From your README.md:

> Write your tests
> 
> Tests must be placed in the ./src/androidTest/groovy directory.
> 
> Write your tests like you would regular spock tests. See the spock-android-sample project and Spock >Framework for more details.

It clearly says: "Tests must be placed in the ./src/androidTest/groovy directory."

**Comment by AndrewReitz** [comment]
That is not an incorrect statement.

**Comment by AndrewReitz** [comment]
If you have a suggestion for an edit, feel free to do a pull request.

**Comment by jaredsburrows** [comment]
Why are you forcing users to put tests in the `androidTest` folder? Why and what are the limitations?

**Comment by AndrewReitz** [comment]
If I remember correctly it's this https://github.com/groovy/groovy-android-gradle-plugin/blob/master/src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy#L77

**Comment by jaredsburrows** [comment]
I guess I could make a pull request there. I would like to be able to use Spock with my current tests. I guess this is just an example repo and not the actual plugin itself. Sorry about the confusion.

**Comment by AndrewReitz** [comment]
The library itself provides some spock extensions and ability to use spock mocks in Android. That's all for now.

**Comment by jaredsburrows** [comment]
Sounds good.
