### ISSUE TITLE
Jacoco integration

### ISSUE THREAD

**Issue by arturonaredo** [pieces029/android-spock#16]
More than an issue is just a question... Mostly all production environments are based on KPIs and that stuff, so a way to measure the "amount" and """quality""" of the tests are needed. Is it possible to integrate the tool with Jacoco coverage tool?

**Comment by AndrewReitz** [comment]
Sorry for the slow response, issues in my projects get melded in with all the projects I follow. I believe the android plugin works with Jacoco, but I haven't played around with it much. Here is a blog post I found. http://hitherejoe.com/wordpress/android-unit-test-coverage-jacoco/ does that help? I would be interested in anything you find too.

**Comment by arturonaredo** [comment]
Closed issue due inactivity :)
