### ISSUE TITLE
Problems using Espresso with android-spock

### ISSUE THREAD

**Issue by bschramke** [pieces029/android-spock#20]
I tried to use espresso along with android-spock. This works fine, as long as my Specification has just one single test method.

If I add a second test which interacts with the activity, these second test hangs because it is waiting for the activity coming up.

I'm not sure if it's an bug or maybe I do something wrong? Or it's just a feature that is still not implemented?

I attached some sample code :
[CalculatorActivitySpec.groovy](https://github.com/AndrewReitz/android-spock/files/810378/CalculatorActivitySpec.groovy.txt) is working perfectly fine.
[OtherCalculatorActivitySpec.groovy](https://github.com/AndrewReitz/android-spock/files/810379/OtherCalculatorActivitySpec.groovy.txt) the first test is passing, the second one hangs.

_EDIT: I was able to solve the Problem. I was still on v1.2.1 and found that there is an attribute runMode introduced with v1.2.2. This is currently neither mentioned in the documentation nor the sample._

**Comment by AndrewReitz** [comment]
Hey @bschramke,

Thanks for reporting this. Could you give a bit more detail on what's going on / what you did to fix this issue so that I can document it?

I've been slowly but surely working up to release 2.0 and defiantly want to make sure it's documented in that release.

Thanks!
