### ISSUE TITLE
Instrumentation method test invocation

### ISSUE THREAD

**Issue by andrzejkaras** [pieces029/android-spock#23]
I have connected android spock according to your instructions in tutorial. Ordinary unit test works excelent, but when I want execute one instrumentation test method error occurs - `Test running failed: No test results. Empty test suite.`. Furthermore, when I execute all methods in instrumentation test class everything works fine. Please, let me know what information you need to solve the problem.

**Comment by AndrewReitz** [comment]
This isn't an issue with Spock, but rather Android Studio / Android. You can't have methods with spaces in them. If you change your tests names from having spaces to having underscores you will be able to run instrumentation tests from Android Studio.

**Comment by andrzejkaras** [comment]
Thank you for help! Im appreciate that.
